# Generated by Django 3.2.9 on 2021-12-03 22:07

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211203_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Аэропорт')),
                ('code_ikao', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Код аэродрома ИКАО')),
                ('lon', models.FloatField(blank=True, default=None, null=True, verbose_name='Долгота (E)')),
                ('lat', models.FloatField(blank=True, default=None, null=True, verbose_name='Широта (N)')),
                ('height', models.FloatField(blank=True, default=None, null=True, verbose_name='Высота над уровнем моря')),
                ('len_vvp', models.FloatField(blank=True, default=None, null=True, verbose_name='Длина ВПП')),
                ('width_vvp', models.FloatField(blank=True, default=None, null=True, verbose_name='Ширина ВПП')),
                ('coating', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Покрытие основной ВПП')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
